Feature: Pushinho Channel on New Push
push-platform/push-apps pull request #1
Opened 2019-09-26 19:04 UTC by matmsa27

2019-09-27 18:00 UTC, johncordeiro requested changes

2019-09-27 18:00 UTC, johncordeiro commented on README.md
> +The idea for this project is: There are a folder `push-public` that contains all features for New Push. `push-public` folder must be couple inside a root for RapidPro project, and then there are all
There is* a folder.

2019-09-27 18:00 UTC, johncordeiro commented on README.md
> +For Run the features For New Push inside [RapidPro](http://rapidpro.github.io/rapidpro/docs/), needs setup RapidPro project, and then setup environment variables for New Push and the libs.
for* New Push. You need* to setup a RapidPro project.

2019-09-27 18:00 UTC, johncordeiro commented on general/channels/types/pushinho/forms.py
> +        max_length=7, help_text=_("Hexa Decimal Colour"), widget=ColorFieldWidget()
Let's use `Color` instead of `Colour`

2019-09-27 18:00 UTC, johncordeiro commented on general/channels/types/pushinho/type.py
> +    configuration_urls = ""
it must be here? or removed?

2019-09-27 18:00 UTC, johncordeiro commented on general/channels/types/pushinho/type.py
> +        dict(link=_("HTML For Pushinho Configuration"), name="pushinho_configuration")
HTML For Pushinho Configuration to `Integrate to your Website`

2019-09-27 18:00 UTC, johncordeiro commented on general/channels/types/pushinho/utils.py
> +        "main_icon_url": main_icon_url,
I suggest using constant that lives in the type instance, instead of hardcoded strings.

2019-09-27 20:54 UTC, dyohan9 commented on general/channels/types/pushinho/tests.py
> +from.type import PushinhoType
Check the import, replace it with the from .type import PushinhoType, a space is missing after the from.

2019-09-27 21:01 UTC, dyohan9 approved these changes

2019-09-30 19:06 UTC, johncordeiro requested changes

2019-09-30 19:06 UTC, johncordeiro commented on general/channels/types/pushinho/forms.py
> +        self.fields["main_icon"].required = False
why not using constants instead of hardcoded strings?

2019-09-30 19:06 UTC, johncordeiro commented on general/channels/types/pushinho/tests.py
> +        post_data["main_icon"] = SimpleUploadedFile(main_icon.name, main_icon.read())
why not using constants here?

2019-09-30 19:06 UTC, johncordeiro commented on general/channels/types/pushinho/tests.py
> +        post_data["main_icon"] = None
why not using constants here?

2019-09-30 19:06 UTC, johncordeiro commented on general/channels/types/pushinho/tests.py
> +        post_data["main_icon"] = SimpleUploadedFile(main_icon.name, main_icon.read())
constants

2019-09-30 19:06 UTC, johncordeiro commented on general/channels/types/pushinho/tests.py
> +            "main_icon_color": "#18fae2",
constants

2019-09-30 19:06 UTC, johncordeiro commented on general/channels/types/pushinho/utils.py
> +        "main_icon_color": data.get("main_icon_color"),
why not using constants for all string keys?

2019-10-03 17:17 UTC, johncordeiro requested changes

2019-10-03 17:17 UTC, johncordeiro commented on general/channels/types/pushinho/forms.py
> +        self.fields[KEYWORD].initial = self.object.config[WELCOME_BUTTON]
Why `KEYWORD` in some cases and `WELCOME_BUTTON` in others?

2019-10-03 19:38 UTC, johncordeiro approved these changes

2019-10-03 19:39 UTC, merged